spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: db/changelog/master.xml

  shell:
    interactive:
      enabled: true